framework:
  cache:
    app: cache.adapter.redis
    default_redis_provider: "redis://localhost:6379"
    pools:
      app.cache.codification:
        name: app.cache.codification # this will be the service's name
        public: true # this will expose the pool as a service
        adapter: cache.app
        default_lifetime: 86400
      app.cache.another_pool:
        name: app.cache.another_pool
        public: true
        adapter: cache.app
        default_lifetime: 600